. "$PSScriptRoot\Functions\GenXdev.Queries.AI\Open-BingCopilotQuery.ps1"
. "$PSScriptRoot\Functions\GenXdev.Queries.AI\Open-ChatGPTQuery.ps1"
. "$PSScriptRoot\Functions\GenXdev.Queries.AI\Open-GithubCopilotQuery.ps1"
. "$PSScriptRoot\Functions\GenXdev.Queries.AI\Open-GoogleGeminiQuery.ps1"
. "$PSScriptRoot\Functions\GenXdev.Queries.AI\Open-XGrokQuery.ps1"
