. "$PSScriptRoot\Functions\GenXdev.Queries.Websites\Open-GameOfLife.ps1"
. "$PSScriptRoot\Functions\GenXdev.Queries.Websites\Open-GenXdevAppCatalog.ps1"
. "$PSScriptRoot\Functions\GenXdev.Queries.Websites\Open-Timeline.ps1"
. "$PSScriptRoot\Functions\GenXdev.Queries.Websites\Open-ViralSimulation.ps1"
. "$PSScriptRoot\Functions\GenXdev.Queries.Websites\Open-Yab.ps1"
. "$PSScriptRoot\Functions\GenXdev.Queries.Websites\Open-YabAIBattle.ps1"
